app = "session-manager"
primary_region = "dfw"

[build]

[env]
  GRPC_PORT = "50051"

[[services]]
  internal_port = 50051
  protocol = "tcp"
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    port = 443
    handlers = ["tls"]

  [services.ports.tls_options]
    alpn = ["h2"]

  [[services.concurrency]]
    type = "connections"
    hard_limit = 500
    soft_limit = 400

  [[services.tcp_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "10s"

[[vm]]
  memory_mb = 512
  cpu_kind = "shared"
  cpus = 1
