# fly.toml — gRPC‑only ghostcache API
app = "session-manager"
primary_region = "dfw"

[build]

[http_service]
  internal_port = 50051
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = "connections"
    soft_limit = 120
    hard_limit = 150

[scale]
  min_machines = 0
  max_machines = 1

[[vm]]
  memory_mb = 512
  cpu_kind  = "shared"
  cpus      = 1